SELECT_ALL_URLS = "SELECT id, name FROM urls ORDER BY id DESC;"
CHECK_FOR_MATCHES = "SELECT id FROM urls WHERE name = (%s);"
ADD_URL = "INSERT INTO urls (name, created_at) VALUES (%s, %s) RETURNING id;"
SELECT_DATA = "SELECT id, name, created_at FROM urls WHERE id = (%s);"
INSERT_CHECK = "INSERT INTO url_checks (url_id, created_at, status_code, h1, title, description) VALUES (%s, %s, %s, %s, %s, %s);"
SELECT_NAME = "SELECT name FROM urls WHERE (id) = (%s);"
SELECT_CHECK_DATA = "SELECT id, created_at, status_code, h1, title, description FROM url_checks WHERE url_id = (%s) ORDER BY id DESC;"
SELECT_PREF = "SELECT created_at, status_code FROM url_checks WHERE url_id = (%s) ORDER BY id DESC;"
