name: Proj-test
on: push
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build-proj
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install requirements
        run: |
          pip install poetry
          make install
      - name: Run lint
        run: make lint

        
